### ISSUE TITLE
Incorrect favicon

### ISSUE THREAD

**Issue by sman591** [codeRIT/coderit.github.io#23]
Our favicon is a... cactus... Rochester's a bit far from Texas.

**Comment by thenaterhood** [comment]
The favicon was (is?) an inside joke among those of us who worked on spinning up the organization initially. It's not an accident.

**Comment by nateperry** [comment]
It was a joke from before we even knew that BrickHack was actually going to happen. Stuart, feel free to correct it. Pretty much everyone who was "in" on the joke is no longer around.

**Comment by piperchester** [comment]
Yes! I'm glad Stuart finally noticed. Part of me wants to keep the cactus, but a bigger part of me knows that it needs to be changed... :fallen_leaf:

**Comment by ColdenCullen** [comment]
But cactus...

**Comment by thenaterhood** [comment]
I don't really have any say here since I'm no longer really involved in codeRIT, and I don't have a big preference either way any way. 

That said, my thoughts are that it is a harmless and amusing quirk of the organization if anyone happens to notice it. I don't think there's necessarily a "need" to change it, but I can understand that for consistent branding it could be a good thing.

**Comment by nateperry** [comment]
It has never been an issue and it is not hurting anything. No one has ever questioned it, and it did not impact our ability to gain sponsorship. It does not *need* to be changed, but it's also not a bad idea to change it. With the success of BrickHack, the CodeRIT site is likely to gain a bit more traffic in the coming year. I personally think it is really up to Stuart as he is the new director of the organization.

**Comment by sman591** [comment]
I'll be changing it for the sake of consistent branding, but it's cool to know it's more than just a random icon.
